
package etu.bookresearchsoap.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Mar 26 14:07:08 CET 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "addBook", namespace = "http://service.bookresearchsoap.etu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addBook", namespace = "http://service.bookresearchsoap.etu/")

public class AddBook {

    @XmlElement(name = "book")
    private etu.bookresearchsoap.model.Book book;

    public etu.bookresearchsoap.model.Book getBook() {
        return this.book;
    }

    public void setBook(etu.bookresearchsoap.model.Book newBook)  {
        this.book = newBook;
    }

}

