
package etu.bookresearchsoap.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Mar 26 14:07:08 CET 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getBookById", namespace = "http://service.bookresearchsoap.etu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBookById", namespace = "http://service.bookresearchsoap.etu/")

public class GetBookById {

    @XmlElement(name = "id")
    private java.lang.String id;

    public java.lang.String getId() {
        return this.id;
    }

    public void setId(java.lang.String newId)  {
        this.id = newId;
    }

}

