
package etu.bookresearchsoap.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Mar 26 14:07:08 CET 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getBookByTitle", namespace = "http://service.bookresearchsoap.etu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBookByTitle", namespace = "http://service.bookresearchsoap.etu/")

public class GetBookByTitle {

    @XmlElement(name = "title")
    private java.lang.String title;

    public java.lang.String getTitle() {
        return this.title;
    }

    public void setTitle(java.lang.String newTitle)  {
        this.title = newTitle;
    }

}

